### PR TITLE
[#152] Fixed workspace list reload after deleting a workspace

### LINKED ISSUE #152: Workspaces list is not refreshed upon delete.
1) Create a WS
2) Go back to the list of WS
3) Go back to the WS detail
4) Delete WS

Now, upon redirect to the WS list, the list still shows the last deleted WS.

Tested on https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/

### PR DESCRIPTION
**Pull request by karelklima**
Resolves #152.

### CODE REVIEW

File: src/components/workspaces/WorkspacesTable.tsx [hunk 1]
```diff
@@ -78,14 +74,14 @@ const WorkspacesTable: React.FC<WorkspacesTableProps> = ({
...
-    : workspacesResource
+  const dataFilter = (data: any[]) =>
+    data.filter((workspace) => (workspace as Workspace).author.id === sub)
 
   return (
     <DataTableSuspense
       columns={columns}
-      resource={resource}
+      resource={workspacesResource}
+      filter={currentUserOnly ? dataFilter : undefined}
```
Comment (psiotwo) [inline src/components/workspaces/WorkspacesTable.tsx:84]: I typically tend to use rather vanilla empty implementations than undefined-checks on both client and server side, but it is probably more a matter of taste.

**Review by psiotwo — APPROVED** [review]
lgtm
