### PR TITLE
[#121] Provide better error report to user if something goes wrong

### LINKED ISSUE #121: Provide better error report to user instead of just generic 500 page

### PR DESCRIPTION
**Pull request by karelklima**
The goal of this PR is to give the user better error report if something goes wrong.

If an error origins from a XHR request, then it looks like this (the server message is displayed):
image

In-app errors are reported as 500 - stack trace or other details are usually meaningless for user, and if someone is interested she can see the full error in console anyway.

Resolves #121

### CODE REVIEW

File: src/i18n/common.cs.json [hunk 1]
```diff
@@ -4,6 +4,7 @@
   "en": "English",
   "pageNotFound": "Stránka nenalezena",
   "somethingWentWrong": "Něco se pokazilo",
+  "somethingWentWrongWithApi": "Něco se pokazilo s API",
```
Comment (psiotwo) [inline src/i18n/common.cs.json:7]: Něco se pokazilo při komunikaci se serverem?

**Review by psiotwo — APPROVED** [review]
The code looks OK, just wondering what amount of details should be provided. 

Haven't tested though.

**Comment by karelklima** [comment]
@psiotwo I consider this report to be temporary and intended mostly for development purposes. We should not show the error details in production eventually, but rather monitor is using a dedicated service like Sentry (#122)

File: src/i18n/common.cs.json (hunk 1 above)
Comment (karelklima) [reply src/i18n/common.cs.json]: Fixed

**Review by psiotwo — APPROVED** [review]
lgtm
